---
- name: Install complete web server
  hosts: all
  become: true
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: installed

  - name : Start httpd service
    service:
      name: httpd
      state: started

  - name: Copy index.html file
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode : 0777

