---
- name: Uninstalling httpd
  hosts: all
  become: true
  tasks:
  - name: Stopping httd service
    service:
      name: httpd
      state: stopped

  - name: Uninstall httpd from nodes
    yum:
      name: httpd
      state: removed

